### ISSUE TITLE
Standalone Mac app cannot export vector graphics

### ISSUE THREAD

**Issue by jfoster17** [glue-viz/glue-standalone-apps#4]
**Describe the bug**
Using the standalone Mac application, I cannot export a figure to a vector format, for pdf/eps/ps/svg I get an error dialog saying:

```
No module named
`matplotlib.backends.backend_{fmt}`
```
Where fmt is the vector format in question. Raster formates, png/jpg/tiff work fine.

**Details:**

- Operating System: MacOS 12.4
- Glue version: 2021.10.0

**Comment by astrofrog** [comment]
@jfoster17 - could you check if this now works correctly? I think it was fixed last year in https://github.com/glue-viz/glue-standalone-apps/commit/2852ed5d1fdfebda6f18fd7185cf4583cdbf9c8c

**Comment by astrofrog** [comment]
Just checked and it works, so closing!
